# Generated by Django 3.2.7 on 2022-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
